### PR TITLE
Run differential tests from Python 3.6 until 3.10

### PR DESCRIPTION
**Pull request by angelonakos**
*Issue #, if available:*

*Description of changes:*

Update GitHub Actions workflow.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by markrtuttle** [comment]
I think it is unlikely this regression test is going to work because the run script in the http repository depends on features not in 3.6.

**Comment by angelonakos** [comment]
> I think it is unlikely this regression test is going to work because the run script in the http repository depends on features not in 3.6.

If we ignore the failed, cancelled checks and merge this PR, then the differential tests in #116 should run with Python versions 3.6 though 3.10, right?

**Comment by markrtuttle** [comment]
I don't understand what this pull request is trying to accomplish.  We know it will fail with 3.6, maybe even 3.7.  Why merge something that we know is hopeless?

**Comment by angelonakos** [comment]
> I don't understand what this pull request is trying to accomplish. We know it will fail with 3.6, maybe even 3.7. Why merge something that we know is hopeless?

I'll convert it again into a draft The PR can be opened again when we expect differential tests to succeed with 3.6, 3.7

**Pull request closed without merging**
